import {Cairo} from "next/font/google";
import "./globals.css";
import Navbar from "./sharedcomponent/navbar";
import Footer from "./sharedcomponent/footer";
import 'bootstrap/dist/css/bootstrap.min.css';
import { ThemeProvider } from "next-themes";

const inter = Cairo({ subsets: ["arabic"],weight:['300','400','700','800'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar">
      <head>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"/>

      </head>
      <body className={inter.className}><ThemeProvider><Navbar/>{children}<Footer/></ThemeProvider></body>
    </html>
  );
}
